# Report Generation Functions

#' Generate Report
#'
#' Generates an HTML report of the Q-method analysis results.
#'
#' @param output_file File path for the output HTML report
#' @param statements Dataframe containing the Q statements
#' @param qsort_data Dataframe containing the Q-sort data
#' @param demographics Dataframe containing demographic data
#' @param personality Dataframe containing personality data
#' @param qmethod_results List containing the results of the Q-method analysis
#' @param correlation_results List containing the results of the correlation analysis
#' @param include_qmethod Whether to include Q-method analysis in the report
#' @param include_demographics Whether to include demographic analysis in the report
#' @param include_personality Whether to include personality analysis in the report
#' @param include_correlation Whether to include correlation analysis in the report
#' @return NULL
generate_report <- function(output_file, statements, qsort_data, demographics, personality,
                           qmethod_results, correlation_results,
                           include_qmethod = TRUE,
                           include_demographics = TRUE,
                           include_personality = TRUE,
                           include_correlation = TRUE) {
  
  # Create temporary Rmd file
  rmd_file <- tempfile(fileext = ".Rmd")
  
  # Write report content to Rmd file
  writeLines(
    c(
      "---",
      "title: \"Q-Method Cybersecurity Study Analysis Report\"",
      paste0("date: \"", format(Sys.Date(), "%B %d, %Y"), "\""),
      "output: html_document",
      "---",
      "",
      "```{r setup, include=FALSE}",
      "knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)",
      "library(ggplot2)",
      "library(knitr)",
      "library(DT)",
      "library(corrplot)",
      "```",
      "",
      "# Introduction",
      "",
      "This report presents the results of a Q-methodology study on cybersecurity attitudes and beliefs. The study involved participants sorting statements related to cybersecurity according to their level of agreement or disagreement.",
      "",
      "## Study Overview",
      "",
      paste0("- Number of statements: ", nrow(statements)),
      paste0("- Number of participants: ", length(unique(qsort_data$participant_id))),
      if (!is.null(demographics)) paste0("- Demographics collected: Yes") else "- Demographics collected: No",
      if (!is.null(personality)) paste0("- Personality traits collected: Yes") else "- Personality traits collected: No",
      "",
      "# Data Summary",
      "",
      "## Q Statements",
      "",
      "```{r statements-table}",
      "kable(statements, caption = \"Q Statements Used in the Study\")",
      "```",
      "",
      if (include_qmethod && !is.null(qmethod_results)) c(
        "# Q-Method Analysis Results",
        "",
        "## Factor Extraction",
        "",
        "```{r factor-extraction}",
        "print(qmethod_results$summary)",
        "```",
        "",
        "## Factor Loadings",
        "",
        "The factor loadings indicate how strongly each participant's Q-sort correlates with each extracted factor. Higher loadings indicate stronger alignment with the factor's viewpoint.",
        "",
        "```{r factor-loadings-table}",
        "kable(qmethod_results$factor_loadings, caption = \"Factor Loadings by Participant\")",
        "```",
        "",
        "```{r factor-loadings-plot, fig.width=10, fig.height=8}",
        "plot_factor_loadings(qmethod_results$factor_loadings)",
        "```",
        "",
        "## Factor Scores",
        "",
        "Factor scores represent how each statement ranks within each factor. Higher scores indicate stronger agreement with the statement within that factor's viewpoint.",
        "",
        "```{r factor-scores-table}",
        "kable(qmethod_results$factor_scores, caption = \"Factor Scores by Statement\")",
        "```",
        "",
        "```{r factor-scores-plot, fig.width=10, fig.height=8}",
        "plot_factor_scores(qmethod_results$factor_scores, statements)",
        "```",
        "",
        "## Consensus and Distinguishing Statements",
        "",
        "### Consensus Statements",
        "",
        "Consensus statements are those that do not distinguish between any pair of factors. These statements are similarly ranked across all factors.",
        "",
        "```{r consensus-statements}",
        "if (nrow(qmethod_results$consensus_statements) > 0) {",
        "  kable(qmethod_results$consensus_statements, caption = \"Consensus Statements\")",
        "} else {",
        "  cat(\"No consensus statements identified.\")",
        "}",
        "```",
        "",
        "### Distinguishing Statements",
        "",
        "Distinguishing statements are those that are ranked significantly differently in one factor compared to other factors.",
        "",
        "```{r distinguishing-statements}",
        "if (nrow(qmethod_results$distinguishing_statements) > 0) {",
        "  kable(qmethod_results$distinguishing_statements, caption = \"Distinguishing Statements\")",
        "} else {",
        "  cat(\"No distinguishing statements identified.\")",
        "}",
        "```",
        "",
        "## Factor Interpretation",
        "",
        "Based on the factor scores and distinguishing statements, we can interpret the factors as representing different viewpoints on cybersecurity:",
        "",
        "```{r factor-interpretation}",
        "# Extract top and bottom statements for each factor",
        "factor_cols <- grep(\"^Factor\", colnames(qmethod_results$factor_scores), value = TRUE)",
        "",
        "for (factor in factor_cols) {",
        "  cat(paste0(\"### \", factor, \"\\n\\n\"))",
        "  ",
        "  # Sort by factor score",
        "  sorted_scores <- qmethod_results$factor_scores[order(-qmethod_results$factor_scores[[factor]]), ]",
        "  ",
        "  # Top 5 statements (most agree)",
        "  cat(\"**Most Agree:**\\n\\n\")",
        "  top_statements <- head(sorted_scores, 5)",
        "  for (i in 1:nrow(top_statements)) {",
        "    cat(paste0(i, \". \", top_statements$Statement[i], \" (\", round(top_statements[[factor]][i], 2), \")\\n\"))",
        "  }",
        "  cat(\"\\n\")",
        "  ",
        "  # Bottom 5 statements (most disagree)",
        "  cat(\"**Most Disagree:**\\n\\n\")",
        "  bottom_statements <- tail(sorted_scores, 5)",
        "  for (i in 1:nrow(bottom_statements)) {",
        "    cat(paste0(i, \". \", bottom_statements$Statement[nrow(bottom_statements) - i + 1], \" (\", ",
        "               round(bottom_statements[[factor]][nrow(bottom_statements) - i + 1], 2), \")\\n\"))",
        "  }",
        "  cat(\"\\n\\n\")",
        "}",
        "```"
      ) else character(0),
      
      if (include_demographics && !is.null(demographics)) c(
        "# Demographic Analysis",
        "",
        "## Demographic Summary",
        "",
        "```{r demographic-summary}",
        "# Age distribution",
        "cat(\"### Age Distribution\\n\\n\")",
        "print(plot_age_summary(demographics))",
        "cat(\"\\n\\n\")",
        "",
        "# Gender distribution",
        "cat(\"### Gender Distribution\\n\\n\")",
        "print(plot_gender_summary(demographics))",
        "cat(\"\\n\\n\")",
        "",
        "# Education distribution",
        "cat(\"### Education Distribution\\n\\n\")",
        "print(plot_education_summary(demographics))",
        "cat(\"\\n\\n\")",
        "",
        "# Job role distribution",
        "cat(\"### Job Role Distribution\\n\\n\")",
        "print(plot_job_role_summary(demographics))",
        "cat(\"\\n\\n\")",
        "",
        "# Experience distribution",
        "cat(\"### Years of Experience Distribution\\n\\n\")",
        "print(plot_experience_summary(demographics))",
        "cat(\"\\n\\n\")",
        "",
        "# Industry distribution",
        "cat(\"### Industry Distribution\\n\\n\")",
        "print(plot_industry_summary(demographics))",
        "cat(\"\\n\\n\")",
        "",
        "# Organization size distribution",
        "cat(\"### Organization Size Distribution\\n\\n\")",
        "print(plot_org_size_summary(demographics))",
        "cat(\"\\n\\n\")",
        "",
        "# Security training distribution",
        "cat(\"### Security Training Distribution\\n\\n\")",
        "print(plot_security_training_summary(demographics))",
        "```",
        "",
        "## Demographics by Factor",
        "",
        "```{r demographics-by-factor, fig.width=10, fig.height=6}",
        "if (!is.null(qmethod_results)) {",
        "  # Job role by factor",
        "  cat(\"### Job Role by Factor\\n\\n\")",
        "  print(plot_demographic_by_factor(demographics, qmethod_results$factor_loadings, \"job_role\", \"Job Role\"))",
        "  cat(\"\\n\\n\")",
        "  ",
        "  # Experience by factor",
        "  cat(\"### Years of Experience by Factor\\n\\n\")",
        "  print(plot_demographic_by_factor(demographics, qmethod_results$factor_loadings, \"years_experience\", \"Years of Experience\"))",
        "  cat(\"\\n\\n\")",
        "  ",
        "  # Security training by factor",
        "  cat(\"### Security Training by Factor\\n\\n\")",
        "  print(plot_demographic_by_factor(demographics, qmethod_results$factor_loadings, \"security_training\", \"Security Training\"))",
        "} else {",
        "  cat(\"Q-method results not available for demographic by factor analysis.\")",
        "}",
        "```"
      ) else character(0),
      
      if (include_personality && !is.null(personality)) c(
        "# Personality Analysis",
        "",
        "## Personality Traits Summary",
        "",
        "```{r personality-summary, fig.width=10, fig.height=6}",
        "print(plot_personality_summary(personality))",
        "```",
        "",
        "## Personality Traits Correlation",
        "",
        "```{r personality-correlation, fig.width=8, fig.height=8}",
        "plot_personality_correlation(personality)",
        "```",
        "",
        "## Personality Traits by Factor",
        "",
        "```{r personality-by-factor, fig.width=10, fig.height=6}",
        "if (!is.null(qmethod_results)) {",
        "  # Security awareness by factor",
        "  cat(\"### Security Awareness by Factor\\n\\n\")",
        "  print(plot_personality_by_factor(personality, qmethod_results$factor_loadings, \"security_awareness\", \"Security Awareness\"))",
        "  cat(\"\\n\\n\")",
        "  ",
        "  # Risk tolerance by factor",
        "  cat(\"### Risk Tolerance by Factor\\n\\n\")",
        "  print(plot_personality_by_factor(personality, qmethod_results$factor_loadings, \"risk_tolerance\", \"Risk Tolerance\"))",
        "  cat(\"\\n\\n\")",
        "  ",
        "  # Conscientiousness by factor",
        "  cat(\"### Conscientiousness by Factor\\n\\n\")",
        "  print(plot_personality_by_factor(personality, qmethod_results$factor_loadings, \"conscientiousness\", \"Conscientiousness\"))",
        "} else {",
        "  cat(\"Q-method results not available for personality by factor analysis.\")",
        "}",
        "```",
        "",
        "## Personality Profiles by Factor",
        "",
        "```{r personality-profiles, fig.width=10, fig.height=6}",
        "if (!is.null(qmethod_results)) {",
        "  print(plot_personality_profiles(personality, qmethod_results$factor_loadings))",
        "} else {",
        "  cat(\"Q-method results not available for personality profile analysis.\")",
        "}",
        "```"
      ) else character(0),
      
      if (include_correlation && !is.null(correlation_results)) c(
        "# Correlation Analysis",
        "",
        "## Correlation Matrix",
        "",
        "```{r correlation-matrix, fig.width=10, fig.height=10}",
        "plot_correlation_matrix(correlation_results$correlation_matrix)",
        "```",
        "",
        "## Significant Correlations",
        "",
        "The table below shows the most significant correlations between variables in the study.",
        "",
        "```{r correlation-table}",
        "# Filter for significant correlations",
        "sig_correlations <- correlation_results$correlation_table[correlation_results$correlation_table$Significance != \"\", ]",
        "",
        "# Display top correlations",
        "if (nrow(sig_correlations) > 0) {",
        "  sig_correlations$Correlation <- round(sig_correlations$Correlation, 3)",
        "  sig_correlations$P_Value <- round(sig_correlations$P_Value, 4)",
        "  kable(head(sig_correlations, 20), caption = \"Top 20 Significant Correlations\")",
        "} else {",
        "  cat(\"No significant correlations found.\")",
        "}",
        "```",
        "",
        "## Key Findings from Correlation Analysis",
        "",
        "```{r correlation-findings}",
        "# Extract correlations with factors",
        "factor_correlations <- correlation_results$correlation_table[",
        "  grepl(\"^Factor\", correlation_results$correlation_table$Variable1) | ",
        "  grepl(\"^Factor\", correlation_results$correlation_table$Variable2), ]",
        "",
        "# Filter for significant correlations",
        "sig_factor_correlations <- factor_correlations[factor_correlations$Significance != \"\", ]",
        "",
        "# Display findings",
        "if (nrow(sig_factor_correlations) > 0) {",
        "  # Group by factor",
        "  factors <- unique(c(",
        "    sig_factor_correlations$Variable1[grepl(\"^Factor\", sig_factor_correlations$Variable1)],",
        "    sig_factor_correlations$Variable2[grepl(\"^Factor\", sig_factor_correlations$Variable2)]",
        "  ))",
        "  ",
        "  for (factor in factors) {",
        "    cat(paste0(\"### \", factor, \"\\n\\n\"))",
        "    ",
        "    # Get correlations for this factor",
        "    factor_cors <- sig_factor_correlations[",
        "      sig_factor_correlations$Variable1 == factor | sig_factor_correlations$Variable2 == factor, ]",
        "    ",
        "    # Sort by absolute correlation",
        "    factor_cors <- factor_cors[order(-abs(factor_cors$Correlation)), ]",
        "    ",
        "    # Display top correlations",
        "    if (nrow(factor_cors) > 0) {",
        "      for (i in 1:min(5, nrow(factor_cors))) {",
        "        var1 <- factor_cors$Variable1[i]",
        "        var2 <- factor_cors$Variable2[i]",
        "        cor_val <- round(factor_cors$Correlation[i], 3)",
        "        sig <- factor_cors$Significance[i]",
        "        ",
        "        # Determine which variable is not the factor",
        "        other_var <- ifelse(var1 == factor, var2, var1)",
        "        ",
        "        cat(paste0(\"- \", other_var, \": \", cor_val, \" \", sig, \"\\n\"))",
        "      }",
        "    } else {",
        "      cat(\"No significant correlations found for this factor.\\n\")",
        "    }",
        "    ",
        "    cat(\"\\n\")",
        "  }",
        "} else {",
        "  cat(\"No significant correlations with factors found.\")",
        "}",
        "```"
      ) else character(0),
      
      "# Conclusion",
      "",
      "This report has presented the results of a Q-methodology study on cybersecurity attitudes and beliefs. The analysis has identified distinct viewpoints on cybersecurity among the participants, and has explored the relationships between these viewpoints and demographic and personality variables.",
      "",
      "## Summary of Key Findings",
      "",
      "```{r conclusion}",
      "if (!is.null(qmethod_results)) {",
      "  # Number of factors",
      "  num_factors <- length(grep(\"^Factor\", colnames(qmethod_results$factor_loadings), value = TRUE))",
      "  cat(paste0(\"- \", num_factors, \" distinct viewpoints on cybersecurity were identified.\\n\"))",
      "  ",
      "  # Consensus",
      "  if (nrow(qmethod_results$consensus_statements) > 0) {",
      "    cat(paste0(\"- \", nrow(qmethod_results$consensus_statements), \" consensus statements were identified, indicating areas of agreement across viewpoints.\\n\"))",
      "  } else {",
      "    cat(\"- No consensus statements were identified, indicating significant disagreement across viewpoints.\\n\")",
      "  }",
      "  ",
      "  # Distinguishing statements",
      "  if (nrow(qmethod_results$distinguishing_statements) > 0) {",
      "    cat(paste0(\"- \", nrow(qmethod_results$distinguishing_statements), \" distinguishing statements were identified, highlighting key differences between viewpoints.\\n\"))",
      "  }",
      "}",
      "",
      "if (!is.null(correlation_results)) {",
      "  # Significant correlations",
      "  sig_correlations <- correlation_results$correlation_table[correlation_results$correlation_table$Significance != \"\", ]",
      "  if (nrow(sig_correlations) > 0) {",
      "    cat(paste0(\"- \", nrow(sig_correlations), \" significant correlations were identified between variables.\\n\"))",
      "    ",
      "    # Top correlation",
      "    top_cor <- sig_correlations[1, ]",
      "    cat(paste0(\"- The strongest correlation was between \", top_cor$Variable1, \" and \", top_cor$Variable2, ",
      "              \" (r = \", round(top_cor$Correlation, 3), \", \", top_cor$Significance, \").\\n\"))",
      "  }",
      "}",
      "```",
      "",
      "## Implications",
      "",
      "The findings of this study have implications for cybersecurity policy, training, and awareness programs. Understanding the different viewpoints on cybersecurity can help organizations tailor their approaches to different groups of employees or stakeholders.",
      "",
      "## Limitations and Future Research",
      "",
      "This study has several limitations that should be considered when interpreting the results:",
      "",
      "- The sample size is relatively small, which limits the generalizability of the findings.",
      "- The Q-sort statements were developed based on existing literature and may not capture all relevant aspects of cybersecurity attitudes and beliefs.",
      "- The study relies on self-reported data, which may be subject to biases.",
      "",
      "Future research could address these limitations by:",
      "",
      "- Conducting similar studies with larger and more diverse samples.",
      "- Developing more comprehensive sets of Q-sort statements.",
      "- Combining Q-methodology with other research methods, such as interviews or observational studies.",
      "- Exploring the relationships between cybersecurity attitudes and actual security behaviors."
    ),
    rmd_file
  )
  
  # Render the report
  rmarkdown::render(rmd_file, output_file = output_file, quiet = TRUE)
  
  # Clean up
  unlink(rmd_file)
  
  return(invisible(NULL))
}
